From debian:latest
MAINTAINER Bob Clapp <bob@sep.stanford.edu>
RUN apt-get -y update &&\
    apt-get -y  install g++ python3-numpy git make gcc libboost-all-dev  libboost-dev &&\
    apt-get -y install  cmake python3-dev python3-pytest python3-numpy-dbg libtbb-dev && \
  apt-get -y clean
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.5 2
#RUN cmake -DCMAKE_INSTALL_PREFIX=/opt/SEP -DCMAKE_CXX_FLAGS="-O3"  -DPYTHON_NUMPY_INCLUDE_DIR=/usr/lib/python3/dist-packages/numpy/core/include ../src
