version: '2'

services:
  ioTest:
    build: .
    image: gcp-io-test
    environment:
      - projectID=earth-clapp
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/gcpcred/gcptest.json
      - region=us-west1
    volumes:
      - /home/bob/gcptest.json:/opt/gcpcred/gcptest.json

    command: /opt/SEP/bin/ReadWriteGCP write aadsfjkskjl/testab 2000 1000 1000  >/tmp/speed&&
       /opt/SEP/bin/ReadWriteGCP read aadsfjkskjl/testab >>/tmp/speed &&
       cat /tmp/speed
#    command: python manage.py runserver 0.0.0.0:8000
